"""Hand-written domain-prompt ensembles used by utils/final_evaluation.py."""

DOMAIN_PROMPTS = {
    "photo": [
        "a real photo",
        "a natural photograph",
        "a realistic photographic image",
        "a color photograph",
        "a close-up photo",
        "a high resolution photograph",
        "a candid photo taken with a camera",
        "a sharp photo with natural lighting",
        "a DSLR photograph",
        "a photo with realistic textures and shadows",
        "a snapshot taken outdoors",
        "a professional stock photo",
        "a documentary style photograph",
        "an unedited camera photo",
        "a photo with shallow depth of field",
        "a true to life color photo",
        "a photograph taken in daylight",
        "a smartphone photo",
        "a detailed real world photograph",
        "a lifelike photographic picture",
    ],
    "cartoon": [
        "a cartoon image",
        "a colorful cartoon illustration",
        "an animated cartoon image",
        "a comic style illustration",
        "a simple cartoon drawing",
        "a brightly colored cartoon image",
        "a vivid colorful animated illustration",
        "a saturated cartoon drawing",
        "a cartoon with bold outlines and flat colors",
        "a children's book cartoon illustration",
        "a cel shaded animation frame",
        "a cute cartoon character drawing",
        "a comic strip panel",
        "a playful cartoon style picture",
        "a cartoon with thick black outlines",
        "a hand drawn animated cartoon",
        "a stylized cartoon with simple shapes",
        "a cartoon illustration with bright flat shading",
        "a funny cartoon doodle in color",
        "a Saturday morning cartoon style image",
    ],
    "deviantart": [
        "a deviantart digital artwork",
        "a digital art illustration",
        "a highly stylized digital artwork",
        "a fan art posted on deviantart",
        "a digital painting by an amateur artist",
        "a fantasy digital artwork",
        "a concept art illustration",
        "a detailed digital painting",
        "a dramatic digital art with vivid lighting",
        "an artwork made with a graphics tablet",
        "a surreal digital artwork",
        "a stylized digital portrait",
        "a manga inspired digital illustration",
        "a digital artwork with glowing effects",
        "a community shared digital art piece",
        "an airbrushed digital painting",
        "a digital art wallpaper",
        "a heavily edited digital artwork",
        "a creative digital art composition",
        "an online gallery digital illustration",
    ],
    "embroidery": [
        "an embroidered artwork",
        "a stitched embroidery design",
        "an image sewn with thread",
        "a cross stitch pattern",
        "an embroidered patch",
        "a thread art picture",
        "a fabric embroidery with visible stitches",
        "a hand embroidered design on cloth",
        "an image made of colored threads",
        "a needlework picture",
        "a satin stitch embroidery",
        "an embroidered badge",
        "a textile art with stitched lines",
        "a machine embroidered logo style image",
        "a tapestry style stitched image",
        "an embroidery hoop artwork",
        "a stitched pattern on linen fabric",
        "an appliqué and thread design",
        "a needlepoint picture",
        "a sewn thread illustration",
    ],
    "graffiti": [
        "a graffiti artwork on a wall",
        "a spray-painted graffiti image",
        "street art graffiti",
        "a mural painted on a brick wall",
        "a graffiti tag in spray paint",
        "an urban street art piece",
        "a colorful graffiti piece on concrete",
        "a stencil graffiti artwork",
        "a wildstyle graffiti lettering image",
        "a spray paint drawing on a city wall",
        "a large wall mural",
        "a graffiti covered wall",
        "an artwork sprayed on a metal shutter",
        "a bold graffiti illustration with drips",
        "a street mural with vivid paint",
        "a graffiti style painting on a building",
        "a rough spray painted figure",
        "an underpass graffiti artwork",
        "a hip hop style graffiti image",
        "a paint can art on a public wall",
    ],
    "graphic": [
        "a vector graphic design",
        "a flat graphic illustration",
        "a clean digital graphic image",
        "a minimalist vector illustration",
        "a flat design icon",
        "a geometric graphic design",
        "a logo style graphic",
        "an infographic style illustration",
        "a poster style graphic design",
        "a clean vector art with solid colors",
        "a simple pictogram",
        "a flat color graphic with no texture",
        "a scalable vector graphic",
        "a modern flat illustration",
        "a graphic design with sharp edges",
        "a clip art style graphic",
        "a corporate style flat illustration",
        "a digital icon with simple shapes",
        "a vector image with gradient fills",
        "a crisp computer graphic design",
    ],
    "misc": [
        "a miscellaneous stylized image",
        "a mixed style artwork",
        "an unusual artistic image",
        "an image in an unclassified art style",
        "a collage of mixed media",
        "an experimental artwork",
        "an abstract stylized picture",
        "an image with an unconventional style",
        "a mixed media illustration",
        "a quirky handmade image",
        "an eclectic artistic composition",
        "an image combining several art styles",
        "a unique stylized artwork",
        "an artistic image of unclear style",
        "a creative hybrid visual style",
        "an odd looking artistic picture",
        "a stylized image that is neither photo nor drawing",
        "a miscellaneous craft image",
        "an unconventional art piece",
        "an artwork made from mixed materials",
    ],
    "origami": [
        "an origami paper figure",
        "a folded paper object",
        "a paper craft origami image",
        "an origami model made of folded paper",
        "a paper folding artwork",
        "a crisp folded paper sculpture",
        "an origami figure with sharp creases",
        "a colorful folded paper craft",
        "a paper model with geometric folds",
        "an origami creature on a table",
        "a figure folded from a single sheet of paper",
        "a handmade paper craft",
        "a folded paper animal",
        "an origami artwork with visible fold lines",
        "a paper art piece with angular facets",
        "a photo of an origami model",
        "a modular origami figure",
        "a washi paper folded figure",
        "a paper cut and folded decoration",
        "a low poly looking paper craft",
    ],
    "sculpture": [
        "a three-dimensional sculpture",
        "a sculpted object",
        "a carved statue artwork",
        "a marble sculpture",
        "a bronze statue",
        "a clay sculpture",
        "a stone carving",
        "a wooden carved figure",
        "a museum sculpture on a pedestal",
        "a statue in a public square",
        "a detailed sculpted figure",
        "a plaster sculpture",
        "a monument statue made of metal",
        "a chiseled stone statue",
        "a modern abstract sculpture",
        "a hand sculpted figurine",
        "a carved relief artwork",
        "a ceramic sculpture",
        "an ice or sand sculpture",
        "a classical sculpture with smooth surfaces",
    ],
    "sketch": [
        "a black and white sketch",
        "a grayscale sketch",
        "a line drawing",
        "a contour drawing",
        "an outline drawing",
        "a monochrome line drawing",
        "a black and white line art image",
        "a clean black outline drawing",
        "a sparse black line drawing on white background",
        "a sketch with only object contours",
        "a white background with thin black outlines",
        "a monochrome contour sketch",
        "a simple object outline drawing",
        "a line-art sketch with no shading",
        "a black ink outline drawing",
        "a sketch made only of edges and contours",
        "a minimal contour-only drawing",
        "a line art illustration",
        "a black and white line art drawing",
        "a minimal line-art image",
    ],
    "sticker": [
        "a sticker illustration",
        "a colorful sticker image",
        "a cutout sticker graphic",
        "a die cut sticker with a white border",
        "a glossy sticker design",
        "a cute sticker on a plain background",
        "a vinyl sticker artwork",
        "a sticker sheet style illustration",
        "an emoji style sticker",
        "a laptop sticker design",
        "a kawaii sticker graphic",
        "a sticker with a thick white outline",
        "a peel off decal image",
        "a messaging app sticker",
        "a badge style sticker",
        "a holographic sticker design",
        "a cartoon sticker cut from paper",
        "a small adhesive label illustration",
        "a sticker pack character image",
        "a bold sticker with flat colors and an outline",
    ],
    "tattoo": [
        "a tattoo design",
        "a black ink tattoo drawing",
        "a tattoo style illustration",
        "a tattoo flash sheet design",
        "a traditional tattoo artwork",
        "a tattoo on skin",
        "a blackwork tattoo design",
        "a bold line tattoo drawing",
        "a tribal style tattoo",
        "a neo traditional tattoo illustration",
        "a tattoo stencil outline",
        "a realistic ink tattoo on an arm",
        "a colorful old school tattoo design",
        "a fine line tattoo",
        "a dotwork tattoo pattern",
        "a tattoo with heavy black shading",
        "a Japanese style tattoo artwork",
        "an inked design on the body",
        "a minimalist tattoo drawing",
        "a tattoo parlor flash art",
    ],
    "toy": [
        "a plastic toy figure",
        "a plush toy",
        "a small toy model",
        "a stuffed animal toy",
        "a toy on a shelf",
        "a wooden toy",
        "a miniature toy figurine",
        "a children's toy photographed up close",
        "a collectible toy figure",
        "a soft toy with fabric texture",
        "a toy made of building blocks",
        "an action figure toy",
        "a toy car model",
        "a colorful playroom toy",
        "a rubber toy",
        "a die-cast toy model",
        "a vinyl collectible figure",
        "a cuddly teddy style plush",
        "a small toy replica of an object",
        "a toy set on a play mat",
    ],
    "videogame": [
        "a video game rendering",
        "a 3d game character render",
        "a computer game screenshot style image",
        "a screenshot from a video game",
        "a game scene with a heads up display",
        "a pixel art video game sprite",
        "a low poly game asset",
        "a console game cutscene frame",
        "a game engine rendered environment",
        "a fantasy role playing game screenshot",
        "an 8-bit retro game image",
        "a game character in a 3d world",
        "an in-game screenshot with stylized graphics",
        "a mobile game artwork",
        "a video game character model",
        "a game level with polygonal textures",
        "a first person game view",
        "a game cover style render",
        "a side scrolling game screenshot",
        "a real time rendered game image",
    ],
    "drawing": [
        "a hand-drawn drawing",
        "a simple doodle drawing",
        "a colored pencil drawing",
        "a pencil drawing on paper",
        "a pen and ink drawing",
        "a crayon drawing",
        "a charcoal drawing",
        "a marker drawing",
        "a child's drawing",
        "a hand-drawn illustration with visible strokes",
        "a pastel drawing",
        "a drawing in a sketchbook",
        "a scribbled doodle",
        "a watercolor and pencil drawing",
        "a rough hand drawn picture",
        "a ballpoint pen drawing",
        "a drawing with shading and hatching",
        "a colored marker illustration on paper",
        "a freehand drawing",
        "an artist's pencil study",
    ],
    "rendering": [
        "a 3d rendered image",
        "a computer generated rendering",
        "a realistic digital rendering",
        "a 3d model render with smooth shading",
        "a ray traced render",
        "a CGI image",
        "a 3d visualization of an object",
        "a clean studio render on a plain background",
        "a photorealistic 3d render",
        "a render from Blender",
        "an architectural visualization render",
        "a product render with soft lighting",
        "a computer generated 3d scene",
        "a 3d illustration with glossy materials",
        "a digital 3d model with reflections",
        "an isometric 3d render",
        "a clay style 3d render",
        "a CAD style rendering",
        "a smooth 3d object with global illumination",
        "a synthetic image created in 3d software",
    ],
    "plastic": [
        "a plastic figure",
        "a shiny plastic object",
        "a molded plastic toy",
        "a glossy injection molded plastic item",
        "a plastic model kit piece",
        "a hard plastic figurine",
        "a smooth plastic surface with highlights",
        "a colorful plastic object",
        "a translucent plastic item",
        "a plastic replica of an object",
        "a polished plastic miniature",
        "a plastic product with a seam line",
        "a cheap plastic novelty item",
        "a plastic container shaped like an object",
        "a molded plastic decoration",
        "a PVC figure",
        "a shiny resin or plastic collectible",
        "a plastic cast model",
        "a matte plastic sculpture",
        "a mass produced plastic figure",
    ],
}
